{% set name = "flask-apispec" %}
{% set version = "0.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a6fedd3a06510a8a19340df676393b336b4ba9d5c159cbb304b62672e3115da

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - flask >=0.10.1
    - marshmallow >=3.0.0
    - webargs >=6.0.0
    - apispec >=4.0.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - flask_apispec
  commands:
    - pip check

about:
  home: https://github.com/jmcarp/flask-apispec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Build and document REST APIs with Flask and apispec

  description: |
    flask-apispec is a lightweight tool for building REST APIs in Flask. 
    flask-apispec uses webargs for request parsing, marshmallow for response
    formatting, and apispec to automatically generate Swagger markup.
    You can use flask-apispec with vanilla Flask or a fuller-featured
    framework like Flask-RESTful.
  doc_url: https://flask-apispec.readthedocs.org/en/latest/
  dev_url: https://github.com/jmcarp/flask-apispec

extra:
  recipe-maintainers:
    - rth
    - synapticarbors
